### ISSUE TITLE
Code generation fails for non retryable error types in activity option

### ISSUE THREAD

**Issue by dimankus** [cludden/protoc-gen-go-temporal#70]
when trying to add non retryable error types to activity options, code generation fails. (it works for workflow options)

adding to example 
https://github.com/cludden/protoc-gen-go-temporal/blob/main/examples/example/proto/example/v1/example.proto#L34

and running "buf generate"
```
rpc Notify(NotifyRequest) returns (google.protobuf.Empty) {
    option (temporal.v1.activity) = {
      start_to_close_timeout: { seconds: 30 }
      retry_policy: {
        max_attempts: 3
        non_retryable_error_types: ["something"]
      }
    };
  }
```

getting error

```
panic: unsupported type for literal: []string

goroutine 1 [running]:
github.com/dave/jennifer/jen.token.render({{0x1012f7276?, 0x0?}, {0x1015c9640?, 0x140004da390?}}, 0x1?, {0x10167d998, 0x14000754420}, 0x1?)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/tokens.go:64 +0x988
github.com/dave/jennifer/jen.(*Statement).render(0x140004da378, 0x14000796c98?, {0x10167d998, 0x14000754420}, 0x140002bd608?)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/statement.go:64 +0x11c
github.com/dave/jennifer/jen.(*Group).renderItems(0x14000494d80, 0x14000796c58?, {0x10167d998, 0x14000754420})
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:118 +0x2d8
github.com/dave/jennifer/jen.(*Group).render(0x14000494d80, 0x14000796c50?, {0x10167d998, 0x14000754420}, 0x140004da348)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:61 +0x110
github.com/dave/jennifer/jen.(*Statement).render(0x140004da348, 0x14000796bd8?, {0x10167d998, 0x14000754420}, 0x140002bd748?)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/statement.go:64 +0x11c
github.com/dave/jennifer/jen.(*Group).renderItems(0x14000494de0, 0x14000796bd0?, {0x10167d998, 0x14000754420})
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:118 +0x2d8
github.com/dave/jennifer/jen.(*Group).render(0x14000494de0, 0x14000796bc8?, {0x10167d998, 0x14000754420}, 0x140004da300)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:61 +0x110
github.com/dave/jennifer/jen.(*Statement).render(0x140004da300, 0x14000796a60?, {0x10167d998, 0x14000754420}, 0x140002bd888?)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/statement.go:64 +0x11c
github.com/dave/jennifer/jen.(*Group).renderItems(0x14000494960, 0x140007968f8?, {0x10167d998, 0x14000754420})
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:118 +0x2d8
github.com/dave/jennifer/jen.(*Group).render(0x14000494960, 0x140007968f0?, {0x10167d998, 0x14000754420}, 0x140004da1e0)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:61 +0x110
github.com/dave/jennifer/jen.(*Statement).render(0x140004da1e0, 0x14000796814?, {0x10167d998, 0x14000754420}, 0x140002bd9f8?)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/statement.go:64 +0x11c
github.com/dave/jennifer/jen.(*Group).renderItems(0x140002642a0, 0x14000600000?, {0x10167d998, 0x14000754420})
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:118 +0x2d8
github.com/dave/jennifer/jen.(*Group).render(0x140002642a0, 0x0?, {0x10167d998, 0x14000754420}, 0x0)
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/group.go:61 +0x110
github.com/dave/jennifer/jen.(*File).Render(0x140004d04d0, {0x10167d978, 0x1400072fc80})
        /home/runner/go/pkg/mod/github.com/dave/jennifer@v1.7.0/jen/jen.go:36 +0x5c
github.com/cludden/protoc-gen-go-temporal/internal/plugin.(*Manifest).render(0x14000624b40)
        /home/runner/work/protoc-gen-go-temporal/protoc-gen-go-temporal/internal/plugin/parse.go:615 +0x54c
github.com/cludden/protoc-gen-go-temporal/internal/plugin.(*Plugin).Run(0x0?, 0x0?)
        /home/runner/work/protoc-gen-go-temporal/protoc-gen-go-temporal/internal/plugin/plugin.go:76 +0x5c
google.golang.org/protobuf/compiler/protogen.run({0x1400008f2b0?, 0x0?}, 0x1400007df18)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.33.0/compiler/protogen/protogen.go:75 +0x114
google.golang.org/protobuf/compiler/protogen.Options.Run({0x1400008f2b0?, 0x0?}, 0x10158c8c4?)
        /home/runner/go/pkg/mod/google.golang.org/protobuf@v1.33.0/compiler/protogen/protogen.go:53 +0x24
main.main()
        /home/runner/work/protoc-gen-go-temporal/protoc-gen-go-temporal/cmd/protoc-gen-go_temporal/main.go:32 +0x124
Failure: plugin go_temporal: exit status 2
```

**Comment by cludden** [comment]
Thanks for catching this! This has been fixed in [v1.13.3](https://github.com/cludden/protoc-gen-go-temporal/releases/tag/v1.13.3).
